-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 13, 2019 at 12:25 PM
-- Server version: 5.7.25
-- PHP Version: 7.3.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `nanolex`
--

-- --------------------------------------------------------

--
-- Table structure for table `aprasymai`
--

CREATE TABLE `aprasymai` (
  `id` int(6) NOT NULL,
  `pavadinimas` text,
  `aprasymas` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `aprasymai`
--

INSERT INTO `aprasymai` (`id`, `pavadinimas`, `aprasymas`) VALUES
(1, 'Convertible_Top_200_ml', 'Nanolex Convertible Top Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for convertible tops while being safe for users and the environment. Convertible soft tops sealed with this product repel oil, water, bird droppings and most other liquid contaminants. This product can also be used on cotton, leather, polyester, or blended fabric.'),
(2, 'Convertible_Top_750_ml', 'Nanolex Convertible Top Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for convertible tops while being safe for users and the environment. Convertible soft tops sealed with this product repel oil, water, bird droppings and most other liquid contaminants. This product can also be used on cotton, leather, polyester, or blended fabric.'),
(3, 'EX_750_ml', 'Nanolex EX is a non-abrasive cleaning agent which removes oils, polish residue, fillers, fats and other contamination to ensure sealants are able to bond properly and fully to the painted surface.\n\nNanolex EX guarantees that surfaces are perfectly-prepared and ready for Nanolex Sealants.'),
(4, 'Final_Finish_200_ml', 'Nanolex Final Finish is a groundbreaking, water-based Quick Detailer with a revolutionary combination of ingredients. Used as a sprayable lacquer cleaner, Nanolex Final Finish easily removes stubborn water spots, light dirt and fingerprints and can also be used as a great drying aid after washing the car. In addition, Nanolex Final Finish forms a long-lasting layer of protection which gives outstanding water beading, a smooth-to-the-touch surface and a deep gloss finish.\n\nThe mild formulation ensures a gentle and refreshing care for all clear lacquer surfaces.'),
(5, 'Final_Finish_750_ml', 'Nanolex Final Finish is a groundbreaking, water-based Quick Detailer with a revolutionary combination of ingredients. Used as a sprayable lacquer cleaner, Nanolex Final Finish easily removes stubborn water spots, light dirt and fingerprints and can also be used as a great drying aid after washing the car. In addition, Nanolex Final Finish forms a long-lasting layer of protection which gives outstanding water beading, a smooth-to-the-touch surface and a deep gloss finish.\n\nThe mild formulation ensures a gentle and refreshing care for all clear lacquer surfaces.'),
(6, 'Finishing-Cut-500_ml', 'Nanolex Finishing Polish 2019 removes fine scratches and holograms from all kinds of automotive paints, leaving a brilliant, high-gloss finish using either rotary or random-orbital machine polishers. Nanolex Finishing Polish 2019 is a micro-polish formulated without the use of silicone oils, waxes and fillers.'),
(7, 'Glass_Cleaner_750_ml', 'Nanolex Glass Cleaner was developed specifically for automotive glass. The innovative formulation guarantees a thorough removal of dirt, grease, insects and waxes easily and with a streak-free finish. Due to the use of special spreading agents, the product provides a smooth gliding action during cleaning, good anti-fogging properties and quickly evaporates without any unwanted ‘build-up’ effect.'),
(8, 'Glass_Polish_100_ml', 'Nanolex Glass Polish is a unique mixture containing micro- abrasives which guarantee that glass surfaces are thoroughly cleansed and perfectly prepared and activated for a treatment with Nanolex Glass Sealant. Shake very well before use.'),
(9, 'Glass_Polish_200_ml', 'Nanolex Glass Polish is a unique mixture containing micro- abrasives which guarantee that glass surfaces are thoroughly cleansed and perfectly prepared and activated for a treatment with Nanolex Glass Sealant. Shake very well before use.'),
(10, 'Heavy-Cut-Polish-1000_ml', 'When full correction is required, Nanolex Heavy Cut Polish reliably removes heavy defects such as random deep scratches, buffer trails and up to 1500 grit sanding marks. The Diminishing Abrasive Technology means the cutting agents break down over longer working periods to leave a uniform finish that refines easily with Nanolex Medium Cut Polish or Nanolex Finishing Polish.\n\nSuitable for all types of automotive paintwork, Heavy Cut Polish is particularly effective on scratch-resistant finishes and can be used with a Rotary or Dual Action machine polisher. For optimum results, use Heavy Cut Polish with a Nanolex Hard Polishing Pad or a wool pad.'),
(11, 'Insect_Remover_750_ml', 'Nanolex Insect Remover is a specialist alkaline cleaner for the residue-free removal of insects, chitin, pollen and other organic residues, readying the car for the pre-wash stage. Carefully-assorted active ingredients and a special surfactant combination penetrate into the dirt, softening it, and then removing it thoroughly and gently, without damaging the paint or any protective coatings.\n\nTo use, apply Nanolex Insect Remover to the whole surface, allow it to react for a short time, and then use a pressure washer to rinse the product off thoroughly. Avoid applying Nanolex Insect Remover in direct sunlight, and do not let the product dry before rinsing.'),
(12, 'Insect_Remover_Concentrate_1000_ml', 'Nanolex Insect Remover Concentrate is a specialist alkaline cleaner for the residue-free removal of insects, chitin, pollen and other organic residues, readying the car for the pre-wash stage. Carefully-assorted active ingredients and a special surfactant combination penetrate into the dirt, softening it, and then removing it thoroughly and gently, without damaging the paint or any protective coatings. To use, apply Nanolex Insect Remover Concentrate to the whole surface, allow it to react for a short time, and then use a pressure washer to rinse the product off thoroughly. Avoid applying Nanolex Insect Remover in direct sunlight, and do not let the product dry before rinsing.'),
(13, 'Interior_Cleaner_750_ml', 'Nanolex Interior Cleaner is designed to gently clean all interior surfaces, such as leather, vinyl and plastic. Mild, low-foaming surfactants with outstanding wetting properties and detergent power remove dirt, oil, grease and nicotine easily and effectively. After using Nanolex Interior Cleaner, surfaces appear clean, fresh, streak free and without glossiness.\n\nNanolex Interior Cleaner is phosphate-free, non-acidic and non-caustic, and was developed, tested and produced in Germany. Shake well before use. Keep out of hands of children.'),
(14, 'Interior_Cleaner_Concentrate_750_ml', 'Nanolex Interior Cleaner Concentrate is designed to gently clean all interior surfaces, such as leather, vinyl and plastic. Mild, low-foaming surfactants with outstanding wetting properties and detergent power remove dirt, oil, grease and nicotine easily and effectively. After using Nanolex Interior Cleaner, surfaces appear clean, fresh, streak free and without glossiness. Nanolex Interior Cleaner Concentrate is phosphate-free, non-acidic and non-caustic, and was developed, tested and produced in Germany. Shake well before use. Keep out of hands of children.\n\n'),
(15, 'Matte_Final_Finish_750_ml', 'Nanolex Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces. It will remove light dust and finger prints between washes or is ideal to use after washing for a perfect finish.\n\nNanolex Matte Final Finish is pH neutral so it will not remove Nanolex Matte Paint Sealant, however it will leave a natural flat sheen to all matte paints, vinyls and surfaces.\n\nWith proper maintenance Nanolex Matte Final Finish will have a durability of approximately 1000 km on the surfaces it was applied to.'),
(16, 'Matte_Reac_Shampoo_750_ml', 'Nanolex Matte Reactivating Shampoo is a specialist car shampoo for matte paints and surfaces. It is completely safe because it does not contain glossing agents or wax that can add shine or gloss to your matte surfaces.\n\nNanolex Matte Reactivating Shampoo is pH neutral and offers good cleaning and lubricating properties to wash your matte paint or surfaces easily. In addition it has advanced nanotechnology that forms a chemical bond and molecular bond with previously applied protective layers and refreshes them, helping to keep your car cleaner for longer.'),
(17, 'Matte_Spray_Sealant_100_ml', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.\n\nWith proper maintenance Nanolex Matte Spray Sealant will have a durability of approximately 8000 km on the surfaces it was applied to.'),
(18, 'Matte_Spray_Sealant_200_ml', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.\n\nWith proper maintenance Nanolex Matte Spray Sealant will have a durability of approximately 8000 km on the surfaces it was applied to.'),
(19, 'Matte-Final-Finish-200ml', 'Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces. It will remove light dust and finger prints between washes or is ideal to use after washing for a perfect finish.\n\nThis Matte Final Finish is pH neutral so it will not remove Nanolex Matte Paint Sealant, however it will leave a natural flat sheen to all matte paints, vinyls and surfaces. With proper maintenance Nanolex Matte Final Finish will have a durability of approximately 1000 km on the surfaces it was applied to.\n\n'),
(20, 'Medium-Cut-500_ml', 'To Refine Corrected Paintwork & Remove Moderate Defects. After paintwork correction, or for moderate blemish removal, Nanolex Medium Cut Polish is a quick and easy solution. Scratches, swirls, holograms and clouding are easily removed even from scratch-resistant paint finishes. In addition, Nanolex Medium Cut Polish will remove 3000 grit sanding marks to leave a refined surface ready for final polishing.'),
(21, 'Microfiber_Wash_750_ml', 'Microfiber Wash is specifically designed for microfiber towels and other accessories. High quality microfiber tools such as polishing pads, drying towels, wash mitts and applicator pads must be properly washed in order to protect their microfiber structure and functionality.\n\nThe special formulation - which is free from artificial fragrances and brighteners - ensures a rigorous, residue-free, yet mild and damage-free wash. This results in longer-lasting microfiber tools with intact capillary structures and unconfined dirt removal capability, not affected by detergent residuals. Amphoteric surfactants with outstanding cleaning properties prevent streaking and smearing when the microfiber tools are used, while waxes, polymers and polishing residuals are completely removed. This specially-designed detergent is also highly suitable for an optimal, residue-free cleaning of polishing pads.'),
(22, 'Nano_One_100_ml', 'Nanolex Nano One is a water-based sealant that simultaneously cleanses, rejuvenates and protects automotive paint. Nanolex Nano One is a creamy, viscous composition based on nano-scale abrasives and wax. Nano One refreshes weathered paint finishes and removes micro scratches - in addition to this, an ultra-thin, surface-bonding wax-hybrid coating is simultaneously applied to the treated surface.\n\nAll this is provided in a simple one-step application.\n\nAs a result, treated surfaces are much more reflective and exceptionally hydrophobic, therefore easier to clean. Washing is much less demanding, less time consuming and the overall effort to maintain a flawless finish is heavily reduced by using Nanolex Nano One.\n\nThe sophisticated chemical composition of Nano One provides a much better durability compared with pure organic waxes.\n\nWith proper maintenance Nanolex Nano One will last approximately 1500 - 3000 miles on the surfaces it was applied to.'),
(23, 'Nano_One_200_ml', 'Nanolex Nano One is a water-based sealant that simultaneously cleanses, rejuvenates and protects automotive paint. Nanolex Nano One is a creamy, viscous composition based on nano-scale abrasives and wax. Nano One refreshes weathered paint finishes and removes micro scratches - in addition to this, an ultra-thin, surface-bonding wax-hybrid coating is simultaneously applied to the treated surface.\n\nAll this is provided in a simple one-step application.\n\nAs a result, treated surfaces are much more reflective and exceptionally hydrophobic, therefore easier to clean. Washing is much less demanding, less time consuming and the overall effort to maintain a flawless finish is heavily reduced by using Nanolex Nano One.\n\nThe sophisticated chemical composition of Nano One provides a much better durability compared with pure organic waxes.\n\nWith proper maintenance Nanolex Nano One will last approximately 1500 - 3000 miles on the surfaces it was applied to.'),
(24, 'ODEX_200_ml', 'Nanolex ODEX is a scent-free, fast acting odor eliminator. Nanolex ODEX chemically bonds to unpleasant, odor-intensive organic substances and neutralizes them very quickly instead of just masking them.\n\nTobacco odor, odors from pets, spilled milk, vomit and most other common sources of unpleasant smell are neutralized within minutes. Simply spray Nanolex ODEX directly onto the affected surfaces.\n\nNanolex ODEX is a water based formulation and is thus safe to use on any surface. '),
(25, 'ODEX_750_ml', 'Nanolex ODEX is a scent-free, fast acting odor eliminator. Nanolex ODEX chemically bonds to unpleasant, odor-intensive organic substances and neutralizes them very quickly instead of just masking them.\n\nTobacco odor, odors from pets, spilled milk, vomit and most other common sources of unpleasant smell are neutralized within minutes. Simply spray Nanolex ODEX directly onto the affected surfaces.\n\nNanolex ODEX is a water based formulation and is thus safe to use on any surface. '),
(26, 'Premium_PA_50_ml_klar.jpg', 'Premium Paint & Alloy Sealant is a new-generation nanotechnology coating which protects and enhances the appearance of automotive paint in one step. Nanolex Premium Paint & Alloy Sealant is a highly advanced coating product that is relatively easy to apply, even for users with only a little experience regarding products of this kind. As a result, treated surfaces are much more reflective and extremely hydrophobic. Washing is much easier and less time consuming, so the overall effort to maintain a flawless finish is heavily reduced due to using Nanolex Premium Paint & Alloy Sealant.\n\nOne layer of Nanolex Premium Paint & Alloy Sealant will repel water, oil and dirt. It also has antistatic characteristics and protects against chemical fallout and biological damage. The sealant is highly resistant to all kinds of detergents and washing equipment. With proper maintenance Nanolex Premium Paint & Alloy Sealant has a longevity of approximately 15,000 km on the surfaces it was applied to.'),
(27, 'Premium_Paint_Alloy_100_ml', 'Premium Paint & Alloy Sealant is a new-generation nanotechnology coating which protects and enhances the appearance of automotive paint in one step. Nanolex Premium Paint & Alloy Sealant is a highly advanced coating product that is relatively easy to apply, even for users with only a little experience regarding products of this kind. As a result, treated surfaces are much more reflective and extremely hydrophobic. Washing is much easier and less time consuming, so the overall effort to maintain a flawless finish is heavily reduced due to using Nanolex Premium Paint & Alloy Sealant.\n\nOne layer of Nanolex Premium Paint & Alloy Sealant will repel water, oil and dirt. It also has antistatic characteristics and protects against chemical fallout and biological damage. The sealant is highly resistant to all kinds of detergents and washing equipment. With proper maintenance Nanolex Premium Paint & Alloy Sealant has a longevity of approximately 15,000 km on the surfaces it was applied to.'),
(28, 'Prewash_Concentrate_1000_ml', 'Very effective, high-foaming, alkaline prewash. The carefully balanced mixture of surfactants, builders and solvents loosen up the grime and remove the more stubborn dirt such as insects, oils, grease and soot. Nanolex Pre-Cleaner is also highly suitable for removal of wax, polish residue and silicones from the car’s exterior to prepare it for an application of Nanolex Paint & Alloy Sealants. And while offering powerful cleaning ability, Nanolex PreWash is safe for most modern materials including more sensitive ones like anodized aluminium.\n\nDilution: 1:30 -1:10, apply using a pump sprayer or a foam lance. Do not let the product dry on the car!\n\nCan be used for the safe removal of wax, polish residue and silicones from the car’s exterior prior to an application of one of the Nanolex Sealants. The corrosion inhibitors in this new formulation ensures compatibility with sensitive materials, such as anodised aluminium.\n\n'),
(29, 'Pure_Shampoo_750_ml', 'Nanolex Pure Shampoo is a highly effective, yet extremely mild (pH-neutral), phosphate and NTA-free exterior car shampoo. The expert combination of surfactants guarantees highly effective cleaning and detergent properties with high foaming and superb slip properties. Nanolex Pure Shampoo is highly concentrated, the recommend dilution for use is 1:200-1:500. Apply Pure Shampoo using a pump sprayer and/or a foam lance.'),
(30, 'Race_Film_Remover_750_ml', 'Nanolex Race Film Remover is a highly efficient cleaner for race track related contamination. Due to the special raw materials it is a highly efficient cleaner and degreaser that easily removes encrusted oil, grease, rubber deposits, wax, bitumen, tar, glue and other kinds of dirt. Nanolex Race Film Remover is free of halogenated hydrocarbons and free of aromatic solvents, it evaporates without any residue. '),
(31, 'Reac_Shampoo_750_ml', 'Nanolex Reactivating Shampoo is designed to clean and protect your car in a single, easy step. While washing your car, the advanced formula reactivates protective layers and refreshes them. Paint surfaces sealed with Nanolex sealants or other last step products become better protected as a result. Water beading is also significantly enhanced (which in turn aids self-cleaning via the ‘Lotus Effect’). Nanolex Reactivating Shampoo also contains a high-tech rinsing aid that will leave your car almost completely dry after thoroughly rinsing it with fresh, clean water. Nanolex Reactivating Shampoo is highly concentrated - mix only 20-25ml of shampoo with 10L of water. '),
(32, 'Si3D_30_ml_glas', 'Based on its unique Si3D technology, Nanolex Car Care offers a range of products specifically developed and designed to fulfill the highest demands and needs of our professional customers. The Nanolex Si3D molecules - precursors of ceramic and hybrid materials - consist of silica, nitrogen, hydrogen and organic compounds such as carbon. These high-performance polymers are all solvent and fluorine free. The additionally-implemented thermoplastic component forms an incredibly hydrophobic, flexible, cross-linked matrix to give an outstanding hardness and durability. Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean properties. Nanolex Si3D can also increase the total hardness of the paint to up to 9H+, adding a clear coat with a color-darkening effect to the treated surface. Depending on the number of applied layers of Nanolex Si3D, the thickness of the coating can vary. The coating thickness, combined with the sophisticated structural nature of the Nanolex Si3D matrix, make the coatings resistant to abrasion caused by frequent washing and resistant against most chemical substances.'),
(33, 'Si3D_50_ml_glas', 'Based on its unique Si3D technology, Nanolex Car Care offers a range of products specifically developed and designed to fulfill the highest demands and needs of our professional customers. The Nanolex Si3D molecules - precursors of ceramic and hybrid materials - consist of silica, nitrogen, hydrogen and organic compounds such as carbon. These high-performance polymers are all solvent and fluorine free. The additionally-implemented thermoplastic component forms an incredibly hydrophobic, flexible, cross-linked matrix to give an outstanding hardness and durability. Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean properties. Nanolex Si3D can also increase the total hardness of the paint to up to 9H+, adding a clear coat with a color-darkening effect to the treated surface. Depending on the number of applied layers of Nanolex Si3D, the thickness of the coating can vary. The coating thickness, combined with the sophisticated structural nature of the Nanolex Si3D matrix, make the coatings resistant to abrasion caused by frequent washing and resistant against most chemical substances.'),
(34, 'Si3D_HD_Flaschen', 'Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean-properties. The additionally-implemented thermoplastic component forms an incredibly hydrophobic, flexible, cross-linked matrix to give outstanding hardness and durability.\n\nSi3D can also increase the total hardness of the paint to up to 9H+ adding a clear coat with a colour-darkening effect to the treated surface. Depending on the number of applied layers of Si3D, the thickness of the coating can vary. The coating thickness, combined with the sophisticated structural nature of the Si3D matrix, make the coatings resistant to abrasion caused by frequent washing and also unaffected by most chemical substances.\n\nUnlike traditional protective coatings such as car wax and conventional polymer coatings, where the protective efficiency decreases with time and from using degreasing or alkaline detergents or because of mechanical removal, Nanolex Si3D coating exhibits outstanding durability and a tough insensitivity to abrasion from frequent washing and the use of strong alkaline or acidic detergents.'),
(35, 'Si3D_Headlight_30ml', 'As headlights and headlight lenses are made of polycarbonate, they require superior protection, especially regarding environmental impacts and sun exposure. Therefore, we are committed to ongoing research and development with the purpose of providing the best products on the market. Nanolex Si3D Headlight has unrivalled characteristics. The sophisticated ingredients on which the coating is based generate an irreversible molecular bonding with the acrylic and polycarbonate surface. UV-stable ceramic and modified acrylic resins form the characteristic 3D structure of the Nanolex coating products, imparting easy-to-clean properties, scratch resistance and adding a brilliant gloss to the treated surface. In addition to the innate UV resistance of the coating, an armor of UV absorbers, radical scavengers and antioxidants guarantee optimal protection of headlights and lenses from UV-induced deterioration and environmental impacts. This cutting-edge technology ensures that our coatings are quick and easy to apply, and that they are of superior quality.'),
(36, 'Si3D_Matte_30_ml_glas', 'Nanolex Si3D Matte is an advanced silica-based coating formulated specifically to protect matt paint finishes and matt vinyl wraps without adding any gloss or otherwise altering their appearance. Developed in Germany, it uses the latest in low volatile content silicon (Si) technology to lay down a film of hybrid siloxane polymers and proprietary thermoplastic components that condenses rapidly to form a flexible matrix-like coating that bonds to treated surfaces at the molecular level. As a result, it provides excellent protection against bird droppings, bug splatter, brake dust, road salt and harmful UV radiation from the sun for up to two years at a time, even on daily drivers (it is impervious to cleaning chemicals and pressure washing).\n\nHowever, the benefits imparted by Nanolex Si3D Matte do not end with outstanding levels of protection and durability. Perhaps equally as importantly, treated surfaces become slicker feeling and more hydrophobic. This latter characteristic not only results in impressive beading upon contact with water, but also produces a strong self-cleaning effect (rainfall beads up and rolls off of treated surfaces, taking freshly deposited contaminants with it, akin to the Lotus Effect in nature). This results in treated bodywork staying appreciably cleaner for longer between routine washes, particularly in the winter. '),
(37, 'SiFinish_200_ml', 'Nanolex SiFinish is a water-based sealant containing silica compounds that are designed to bond to painted and coated surfaces. Nanolex SiFinish offers an incredibly high-gloss shine combined with outstanding water beading performance and leaves the surface smooth to the touch. Nanolex SiFinish is designed to prevent water spotting, acting as a protective layer and lasting multiple months with just one application. Nanolex SiFinish provides excellent protection for months by itself, and when used on top of previously-applied Nanolex coatings it will prolong the durability significantly, as well as leaving the paintwork looking as if a fresh coat of sealant had just been applied. Nanolex SiFinish is designed to prevent water spotting, acting as a protective layer and lasting multiple months with just one application. Nanolex SiFinish provides excellent protection for months by itself, and when used on top of previously-applied Nanolex coatings it will prolong the durability significantly, as well as leaving the paintwork looking as if a fresh coat of sealant had just been applied.'),
(38, 'SiShield_30ml', 'Nanolex SiShield is a ceramic coating developed to provide outstanding chemical and mechanical resistancy combined with great ease of use. Nanolex SiShield provides superb corrosion protection and hardness for all painted surfaces as well as metal and hard plastics. Thanks to a very high level of hydrophobicity and density the layer formed by Nanolex SiShield will provide outstanding easy-to-clean properties. Nanolex SiShield was developed, tested and produced in Germany.'),
(39, 'Spray_Sealant_100_ml', 'Spray Sealant is an advanced formulation based on nanotechnology that protects and enhances all painted surfaces as well as metal and exterior plastics. Nanolex Spray Sealant is based on the chemical sol-gel process which allows the nano-scale particles of SiO2 to self-organise into an interlaced layer and form a covalent (=permanent) bond with the surface at a molecular level.\n\nSurfaces protected with a layer of Nanolex Spray Sealant are much smoother, more reflective and extremely hydrophobic. Washing is therefore much easier and less time-consuming, plus cleaning intervals are substantially increased and the overall effort to maintain a flawless finish is heavily reduced. With proper maintenance Nanolex Spray Sealant has a longevity of approximately 7,000 km on the surfaces it was applied to.\n\nAdds protection:\nEmits strong fumes\nApplication method: by Hand only\nDurability: 6 months+ (7000 km.)\nRecommended for: Cool colours & metallic/pearlescent finishes'),
(40, 'Spray_Sealant_200_ml', 'Spray Sealant is an advanced formulation based on nanotechnology that protects and enhances all painted surfaces as well as metal and exterior plastics. Nanolex Spray Sealant is based on the chemical sol-gel process which allows the nano-scale particles of SiO2 to self-organise into an interlaced layer and form a covalent (=permanent) bond with the surface at a molecular level.\n\nSurfaces protected with a layer of Nanolex Spray Sealant are much smoother, more reflective and extremely hydrophobic. Washing is therefore much easier and less time-consuming, plus cleaning intervals are substantially increased and the overall effort to maintain a flawless finish is heavily reduced. With proper maintenance Nanolex Spray Sealant has a longevity of approximately 7,000 km on the surfaces it was applied to.\n\nAdds protection:\nEmits strong fumes\nApplication method: by Hand only\nDurability: 6 months+ (7000 km.)\nRecommended for: Cool colours & metallic/pearlescent finishes'),
(41, 'Spray_Sealant_750_ml', 'Spray Sealant is an advanced formulation based on nanotechnology that protects and enhances all painted surfaces as well as metal and exterior plastics. Nanolex Spray Sealant is based on the chemical sol-gel process which allows the nano-scale particles of SiO2 to self-organise into an interlaced layer and form a covalent (=permanent) bond with the surface at a molecular level.\n\nSurfaces protected with a layer of Nanolex Spray Sealant are much smoother, more reflective and extremely hydrophobic. Washing is therefore much easier and less time-consuming, plus cleaning intervals are substantially increased and the overall effort to maintain a flawless finish is heavily reduced. With proper maintenance Nanolex Spray Sealant has a longevity of approximately 7,000 km on the surfaces it was applied to.\n\nAdds protection:\nEmits strong fumes\nApplication method: by Hand only\nDurability: 6 months+ (7000 km.)\nRecommended for: Cool colours & metallic/pearlescent finishes'),
(42, 'Tar_Remover_750_ml', 'Nanolex Tar Remover is a solvent-based specialist cleaner for the effortless removal of tar and bitumen. Free of halogenated hydrocarbons, it is suitable for all solvent-resistant surfaces and materials.\n\nApply the product undiluted to the dry surface, and allow it to react for a short time. When necessary, finish by hand and rinse off with a pressure washer appliance, or use a microfiber cloth to wipe off any residue.'),
(43, 'Textile_Leather_200_ml', 'Nanolex Textile and Leather Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for textile and leather while being safe for users and the environment. Surfaces sealed with this product repel oil, water and most other common kinds of liquid contaminants. Nanolex Textile & Leather Sealant can also be used on cotton, leather, polyester, or blended fabric. Nanolex Textile & Leather Sealant was developed, tested and produced in Germany.'),
(44, 'Textile_Leather_750_ml', 'Nanolex Textile and Leather Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for textile and leather while being safe for users and the environment. Surfaces sealed with this product repel oil, water and most other common kinds of liquid contaminants. Nanolex Textile & Leather Sealant can also be used on cotton, leather, polyester, or blended fabric. Nanolex Textile & Leather Sealant was developed, tested and produced in Germany.'),
(45, 'Tire_Rubber_750_ml', 'Nanolex Tire & Rubber Restorer is based upon an optimized, UV resistant formulation which restores tires and rubber trim to their natural appearance. The deeply-penetrating raw materials in Nanolex Tire & Rubber Restorer provide treated surfaces with a long-lasting and original appearance.\n\nWith proper maintenance Nanolex Spray Sealant will have a durability of approximately 1000 km on the surfaces it was applied to.\n\nSpecifications:\n\nSolvent-based\nAdds protection\nUV protection\nShine level: Medium\nDurability: 3 weeks+'),
(46, 'Trim_Rejuvenator_100_ml', 'The exterior plastic trim parts of a car are exposed to many damaging environmental impacts. UV-radiation and heat can damage the plastic trim, turning it grey and making it brittle. Frost, salt, strong and aggressive cleaners, acid rain as well as mechanical abrasion have an extremely detrimental effect on plastic parts, and cause them deteriorate quickly. The special, deeply-penetrating ingredients of Nanolex Trim Rejuvenator ensure that the trim does not fade or become brittle. The typical effects of weathering and greying are also prevented. Nanolex Trim Rejuvantor cleanses gently and adds durability, plus it penetrates the surfaces easily and quickly without adding a greasy finish or leaving an artificial shine.'),
(47, 'Trim_Rejuvenator_200_ml', 'The exterior plastic trim parts of a car are exposed to many damaging environmental impacts. UV-radiation and heat can damage the plastic trim, turning it grey and making it brittle. Frost, salt, strong and aggressive cleaners, acid rain as well as mechanical abrasion have an extremely detrimental effect on plastic parts, and cause them deteriorate quickly. The special, deeply-penetrating ingredients of Nanolex Trim Rejuvenator ensure that the trim does not fade or become brittle. The typical effects of weathering and greying are also prevented. Nanolex Trim Rejuvantor cleanses gently and adds durability, plus it penetrates the surfaces easily and quickly without adding a greasy finish or leaving an artificial shine.'),
(48, 'Trim_Rejuvenator_750_ml', 'The exterior plastic trim parts of a car are exposed to many damaging environmental impacts. UV-radiation and heat can damage the plastic trim, turning it grey and making it brittle. Frost, salt, strong and aggressive cleaners, acid rain as well as mechanical abrasion have an extremely detrimental effect on plastic parts, and cause them deteriorate quickly. The special, deeply-penetrating ingredients of Nanolex Trim Rejuvenator ensure that the trim does not fade or become brittle. The typical effects of weathering and greying are also prevented. Nanolex Trim Rejuvantor cleanses gently and adds durability, plus it penetrates the surfaces easily and quickly without adding a greasy finish or leaving an artificial shine.'),
(49, 'Ultra_Glass_100_ml', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology. This coating forms a chemical bond with the glass it is applied to. Nanolex Ultra Glass sealant drastically improves visibility and safety under wet weather conditions, with superior optical clarity. Coated glass surfaces permanently repel water to an outstanding degree and require significantly less cleaning, so saving you time and money. The build up of ice on the glass surfaces is delayed, once ice has set on the surface it can be removed very easily. Raindrops are blown off by the airflow when driving speeds exceed 60 Km. The durability of Nanolex Ultra Glass Sealant is outstanding, with a longevity of at least 18 months or 30,000 km.'),
(50, 'Ultra_Matte_50_ml', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.'),
(51, 'Ultra_Matte_100_ml', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.'),
(52, 'Ultra-Glass_30_ml', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology. This coating forms a chemical bond with the glass it is applied to. Nanolex Ultra Glass sealant drastically improves visibility and safety under wet weather conditions, with superior optical clarity. Coated glass surfaces permanently repel water to an outstanding degree and require significantly less cleaning, so saving you time and money. The build up of ice on the glass surfaces is delayed, once ice has set on the surface it can be removed very easily. Raindrops are blown off by the airflow when driving speeds exceed 60 Km. The durability of Nanolex Ultra Glass Sealant is outstanding, with a longevity of at least 18 months or 30,000 km.'),
(53, 'Urban_Glass_100_ml', 'Nanolex Urban Glass Sealant is an advanced, solvent-based coating which forms a barrier against water, oil and grime on automotive glass surfaces. Nanolex Urban Glass Sealant combines a high-tech composite material with reactive compounds that form a fully-transparent, highly hydrophobic, non-stick coating that gives outstanding protection to glass surfaces in urban areas. Nanolex Urban Glass Sealant improves visibility and therefore driving comfort in bad weather conditions, reducing the need to use windscreen wipers and screen wash greatly. In addition grime and bug splatter can be easily washed off and de-icing requires much less effort too. Raindrops are dispersed by the airflow when driving speeds exceed 40 Km/h. The durability of Nanolex Urban Glass Sealant is excellent, with a longevity of at least 4-6 months or 6000 km. Nanolex Urban Glass Sealant was developed, tested and manufactured in Germany.'),
(54, 'WashCoat_200_ml', 'Nanolex WashCoat is an incredibly quick and effective way to protect and maintain exterior automotive surfaces. WashCoat is applied to the car after washing, whilst the car is still wet. It forms a chemical bond with the paint and refreshes previously-applied protective layers. Both the gloss level of the paint and the water beading properties are highly increased after a treatment with WashCoat. Your car will also stay cleaner for longer, and will be easier to wash. WashCoat can be applied using a foam lance or a pump sprayer.'),
(55, 'WashCoat_750_ml', 'Nanolex WashCoat is an incredibly quick and effective way to protect and maintain exterior automotive surfaces. WashCoat is applied to the car after washing, whilst the car is still wet. It forms a chemical bond with the paint and refreshes previously-applied protective layers. Both the gloss level of the paint and the water beading properties are highly increased after a treatment with WashCoat. Your car will also stay cleaner for longer, and will be easier to wash. WashCoat can be applied using a foam lance or a pump sprayer.'),
(56, 'Wheel_cleaner_Iron_remover_750_ml', 'Nanolex Wheel Cleaner & Iron Remover is a highly effective and extremely fast-acting wheel cleaner and iron contamination remover. It is less aggressive than traditional acidic wheel cleaners, yet just as powerful.\n\nUpon contact with the surface its effective formulation dissolves all iron contamination, including harmful brake dust.\n\nAn innovative colour change mechanism - which turns the product from clear to red - indicates when the iron particles have been solved and can be safely rinsed away.\n\nNanolex Wheel Cleaner & Iron Remover also reduces the need to agitate treated surfaces, due to its unique viscous formulation and superior dwell time.');

-- --------------------------------------------------------

--
-- Table structure for table `aprasymaiGeri`
--

CREATE TABLE `aprasymaiGeri` (
  `id` int(6) NOT NULL,
  `pavadinimas` text,
  `aprasymas` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `aprasymaiGeri`
--

INSERT INTO `aprasymaiGeri` (`id`, `pavadinimas`, `aprasymas`) VALUES
(1, 'Convertible Top Sealant', 'Nanolex Convertible Top Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for convertible tops while being safe for users and the environment. Convertible soft tops sealed with this product repel oil, water, bird droppings and most other liquid contaminants. This product can also be used on cotton, leather, polyester, or blended fabric.'),
(2, 'EX', 'Nanolex EX is a non-abrasive cleaning agent which removes oils, polish residue, fillers, fats and other contamination to ensure sealants are able to bond properly and fully to the painted surface.\n\nNanolex EX guarantees that surfaces are perfectly-prepared and ready for Nanolex Sealants.'),
(3, 'Final Finish', 'Nanolex Final Finish is a groundbreaking, water-based Quick Detailer with a revolutionary combination of ingredients. Used as a sprayable lacquer cleaner, Nanolex Final Finish easily removes stubborn water spots, light dirt and fingerprints and can also be used as a great drying aid after washing the car. In addition, Nanolex Final Finish forms a long-lasting layer of protection which gives outstanding water beading, a smooth-to-the-touch surface and a deep gloss finish.\n\nThe mild formulation ensures a gentle and refreshing care for all clear lacquer surfaces.'),
(4, 'Finishing-Cut', 'Nanolex Finishing Polish 2019 removes fine scratches and holograms from all kinds of automotive paints, leaving a brilliant, high-gloss finish using either rotary or random-orbital machine polishers. Nanolex Finishing Polish 2019 is a micro-polish formulated without the use of silicone oils, waxes and fillers.'),
(5, 'Glass Cleaner', 'Nanolex Glass Cleaner was developed specifically for automotive glass. The innovative formulation guarantees a thorough removal of dirt, grease, insects and waxes easily and with a streak-free finish. Due to the use of special spreading agents, the product provides a smooth gliding action during cleaning, good anti-fogging properties and quickly evaporates without any unwanted ‘build-up’ effect.'),
(6, 'Glass Polish', 'Nanolex Glass Polish is a unique mixture containing micro- abrasives which guarantee that glass surfaces are thoroughly cleansed and perfectly prepared and activated for a treatment with Nanolex Glass Sealant. Shake very well before use.'),
(7, 'Heavy-Cut Polish', 'When full correction is required, Nanolex Heavy Cut Polish reliably removes heavy defects such as random deep scratches, buffer trails and up to 1500 grit sanding marks. The Diminishing Abrasive Technology means the cutting agents break down over longer working periods to leave a uniform finish that refines easily with Nanolex Medium Cut Polish or Nanolex Finishing Polish.\n\nSuitable for all types of automotive paintwork, Heavy Cut Polish is particularly effective on scratch-resistant finishes and can be used with a Rotary or Dual Action machine polisher. For optimum results, use Heavy Cut Polish with a Nanolex Hard Polishing Pad or a wool pad.'),
(8, 'Insect Remover', 'Nanolex Insect Remover is a specialist alkaline cleaner for the residue-free removal of insects, chitin, pollen and other organic residues, readying the car for the pre-wash stage. Carefully-assorted active ingredients and a special surfactant combination penetrate into the dirt, softening it, and then removing it thoroughly and gently, without damaging the paint or any protective coatings.\n\nTo use, apply Nanolex Insect Remover to the whole surface, allow it to react for a short time, and then use a pressure washer to rinse the product off thoroughly. Avoid applying Nanolex Insect Remover in direct sunlight, and do not let the product dry before rinsing.'),
(9, 'Insect Remover Concentrate', 'Nanolex Insect Remover Concentrate is a specialist alkaline cleaner for the residue-free removal of insects, chitin, pollen and other organic residues, readying the car for the pre-wash stage. Carefully-assorted active ingredients and a special surfactant combination penetrate into the dirt, softening it, and then removing it thoroughly and gently, without damaging the paint or any protective coatings. To use, apply Nanolex Insect Remover Concentrate to the whole surface, allow it to react for a short time, and then use a pressure washer to rinse the product off thoroughly. Avoid applying Nanolex Insect Remover in direct sunlight, and do not let the product dry before rinsing.'),
(10, 'Interior Cleaner', 'Nanolex Interior Cleaner is designed to gently clean all interior surfaces, such as leather, vinyl and plastic. Mild, low-foaming surfactants with outstanding wetting properties and detergent power remove dirt, oil, grease and nicotine easily and effectively. After using Nanolex Interior Cleaner, surfaces appear clean, fresh, streak free and without glossiness.\n\nNanolex Interior Cleaner is phosphate-free, non-acidic and non-caustic, and was developed, tested and produced in Germany. Shake well before use. Keep out of hands of children.'),
(11, 'Interior Cleaner Concentrate', 'Nanolex Interior Cleaner Concentrate is designed to gently clean all interior surfaces, such as leather, vinyl and plastic. Mild, low-foaming surfactants with outstanding wetting properties and detergent power remove dirt, oil, grease and nicotine easily and effectively. After using Nanolex Interior Cleaner, surfaces appear clean, fresh, streak free and without glossiness. Nanolex Interior Cleaner Concentrate is phosphate-free, non-acidic and non-caustic, and was developed, tested and produced in Germany. Shake well before use. Keep out of hands of children.\n\n'),
(12, 'Matte Final Finish', 'Nanolex Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces. It will remove light dust and finger prints between washes or is ideal to use after washing for a perfect finish.\n\nNanolex Matte Final Finish is pH neutral so it will not remove Nanolex Matte Paint Sealant, however it will leave a natural flat sheen to all matte paints, vinyls and surfaces.\n\nWith proper maintenance Nanolex Matte Final Finish will have a durability of approximately 1000 km on the surfaces it was applied to.'),
(13, 'Matte Reactivating Shampoo', 'Nanolex Matte Reactivating Shampoo is a specialist car shampoo for matte paints and surfaces. It is completely safe because it does not contain glossing agents or wax that can add shine or gloss to your matte surfaces.\n\nNanolex Matte Reactivating Shampoo is pH neutral and offers good cleaning and lubricating properties to wash your matte paint or surfaces easily. In addition it has advanced nanotechnology that forms a chemical bond and molecular bond with previously applied protective layers and refreshes them, helping to keep your car cleaner for longer.'),
(14, 'Matte Spray Sealant', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.\n\nWith proper maintenance Nanolex Matte Spray Sealant will have a durability of approximately 8000 km on the surfaces it was applied to.'),
(15, 'Matte Final Finish', 'Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces. It will remove light dust and finger prints between washes or is ideal to use after washing for a perfect finish.\n\nThis Matte Final Finish is pH neutral so it will not remove Nanolex Matte Paint Sealant, however it will leave a natural flat sheen to all matte paints, vinyls and surfaces. With proper maintenance Nanolex Matte Final Finish will have a durability of approximately 1000 km on the surfaces it was applied to.\n\n'),
(16, 'Medium-Cut 500', 'To Refine Corrected Paintwork & Remove Moderate Defects. After paintwork correction, or for moderate blemish removal, Nanolex Medium Cut Polish is a quick and easy solution. Scratches, swirls, holograms and clouding are easily removed even from scratch-resistant paint finishes. In addition, Nanolex Medium Cut Polish will remove 3000 grit sanding marks to leave a refined surface ready for final polishing.'),
(17, 'Microfiber Wash', 'Microfiber Wash is specifically designed for microfiber towels and other accessories. High quality microfiber tools such as polishing pads, drying towels, wash mitts and applicator pads must be properly washed in order to protect their microfiber structure and functionality.\n\nThe special formulation - which is free from artificial fragrances and brighteners - ensures a rigorous, residue-free, yet mild and damage-free wash. This results in longer-lasting microfiber tools with intact capillary structures and unconfined dirt removal capability, not affected by detergent residuals. Amphoteric surfactants with outstanding cleaning properties prevent streaking and smearing when the microfiber tools are used, while waxes, polymers and polishing residuals are completely removed. This specially-designed detergent is also highly suitable for an optimal, residue-free cleaning of polishing pads.'),
(18, 'Nano One', 'Nanolex Nano One is a water-based sealant that simultaneously cleanses, rejuvenates and protects automotive paint. Nanolex Nano One is a creamy, viscous composition based on nano-scale abrasives and wax. Nano One refreshes weathered paint finishes and removes micro scratches - in addition to this, an ultra-thin, surface-bonding wax-hybrid coating is simultaneously applied to the treated surface.\n\nAll this is provided in a simple one-step application.\n\nAs a result, treated surfaces are much more reflective and exceptionally hydrophobic, therefore easier to clean. Washing is much less demanding, less time consuming and the overall effort to maintain a flawless finish is heavily reduced by using Nanolex Nano One.\n\nThe sophisticated chemical composition of Nano One provides a much better durability compared with pure organic waxes.\n\nWith proper maintenance Nanolex Nano One will last approximately 1500 - 3000 miles on the surfaces it was applied to.'),
(19, 'ODEX', 'Nanolex ODEX is a scent-free, fast acting odor eliminator. Nanolex ODEX chemically bonds to unpleasant, odor-intensive organic substances and neutralizes them very quickly instead of just masking them.\n\nTobacco odor, odors from pets, spilled milk, vomit and most other common sources of unpleasant smell are neutralized within minutes. Simply spray Nanolex ODEX directly onto the affected surfaces.\n\nNanolex ODEX is a water based formulation and is thus safe to use on any surface. '),
(20, 'Premium Paint & Alloy Sealant', 'Premium Paint & Alloy Sealant is a new-generation nanotechnology coating which protects and enhances the appearance of automotive paint in one step. Nanolex Premium Paint & Alloy Sealant is a highly advanced coating product that is relatively easy to apply, even for users with only a little experience regarding products of this kind. As a result, treated surfaces are much more reflective and extremely hydrophobic. Washing is much easier and less time consuming, so the overall effort to maintain a flawless finish is heavily reduced due to using Nanolex Premium Paint & Alloy Sealant.\n\nOne layer of Nanolex Premium Paint & Alloy Sealant will repel water, oil and dirt. It also has antistatic characteristics and protects against chemical fallout and biological damage. The sealant is highly resistant to all kinds of detergents and washing equipment. With proper maintenance Nanolex Premium Paint & Alloy Sealant has a longevity of approximately 15,000 km on the surfaces it was applied to.'),
(21, 'Prewash Concentrate', 'Very effective, high-foaming, alkaline prewash. The carefully balanced mixture of surfactants, builders and solvents loosen up the grime and remove the more stubborn dirt such as insects, oils, grease and soot. Nanolex Pre-Cleaner is also highly suitable for removal of wax, polish residue and silicones from the car’s exterior to prepare it for an application of Nanolex Paint & Alloy Sealants. And while offering powerful cleaning ability, Nanolex PreWash is safe for most modern materials including more sensitive ones like anodized aluminium.\n\nDilution: 1:30 -1:10, apply using a pump sprayer or a foam lance. Do not let the product dry on the car!\n\nCan be used for the safe removal of wax, polish residue and silicones from the car’s exterior prior to an application of one of the Nanolex Sealants. The corrosion inhibitors in this new formulation ensures compatibility with sensitive materials, such as anodised aluminium.\n\n'),
(22, 'Pure Shampoo', 'Nanolex Pure Shampoo is a highly effective, yet extremely mild (pH-neutral), phosphate and NTA-free exterior car shampoo. The expert combination of surfactants guarantees highly effective cleaning and detergent properties with high foaming and superb slip properties. Nanolex Pure Shampoo is highly concentrated, the recommend dilution for use is 1:200-1:500. Apply Pure Shampoo using a pump sprayer and/or a foam lance.'),
(23, 'Race Film Remover', 'Nanolex Race Film Remover is a highly efficient cleaner for race track related contamination. Due to the special raw materials it is a highly efficient cleaner and degreaser that easily removes encrusted oil, grease, rubber deposits, wax, bitumen, tar, glue and other kinds of dirt. Nanolex Race Film Remover is free of halogenated hydrocarbons and free of aromatic solvents, it evaporates without any residue. '),
(24, 'Reactivating Shampoo', 'Nanolex Reactivating Shampoo is designed to clean and protect your car in a single, easy step. While washing your car, the advanced formula reactivates protective layers and refreshes them. Paint surfaces sealed with Nanolex sealants or other last step products become better protected as a result. Water beading is also significantly enhanced (which in turn aids self-cleaning via the ‘Lotus Effect’). Nanolex Reactivating Shampoo also contains a high-tech rinsing aid that will leave your car almost completely dry after thoroughly rinsing it with fresh, clean water. Nanolex Reactivating Shampoo is highly concentrated - mix only 20-25ml of shampoo with 10L of water. '),
(25, 'Si3D', 'Based on its unique Si3D technology, Nanolex Car Care offers a range of products specifically developed and designed to fulfill the highest demands and needs of our professional customers. The Nanolex Si3D molecules - precursors of ceramic and hybrid materials - consist of silica, nitrogen, hydrogen and organic compounds such as carbon. These high-performance polymers are all solvent and fluorine free. The additionally-implemented thermoplastic component forms an incredibly hydrophobic, flexible, cross-linked matrix to give an outstanding hardness and durability. Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean properties. Nanolex Si3D can also increase the total hardness of the paint to up to 9H+, adding a clear coat with a color-darkening effect to the treated surface. Depending on the number of applied layers of Nanolex Si3D, the thickness of the coating can vary. The coating thickness, combined with the sophisticated structural nature of the Nanolex Si3D matrix, make the coatings resistant to abrasion caused by frequent washing and resistant against most chemical substances.'),
(26, 'Si3D HD', 'Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean-properties. The additionally-implemented thermoplastic component forms an incredibly hydrophobic, flexible, cross-linked matrix to give outstanding hardness and durability.\n\nSi3D can also increase the total hardness of the paint to up to 9H+ adding a clear coat with a colour-darkening effect to the treated surface. Depending on the number of applied layers of Si3D, the thickness of the coating can vary. The coating thickness, combined with the sophisticated structural nature of the Si3D matrix, make the coatings resistant to abrasion caused by frequent washing and also unaffected by most chemical substances.\n\nUnlike traditional protective coatings such as car wax and conventional polymer coatings, where the protective efficiency decreases with time and from using degreasing or alkaline detergents or because of mechanical removal, Nanolex Si3D coating exhibits outstanding durability and a tough insensitivity to abrasion from frequent washing and the use of strong alkaline or acidic detergents.'),
(27, 'Si3D Headlight', 'As headlights and headlight lenses are made of polycarbonate, they require superior protection, especially regarding environmental impacts and sun exposure. Therefore, we are committed to ongoing research and development with the purpose of providing the best products on the market. Nanolex Si3D Headlight has unrivalled characteristics. The sophisticated ingredients on which the coating is based generate an irreversible molecular bonding with the acrylic and polycarbonate surface. UV-stable ceramic and modified acrylic resins form the characteristic 3D structure of the Nanolex coating products, imparting easy-to-clean properties, scratch resistance and adding a brilliant gloss to the treated surface. In addition to the innate UV resistance of the coating, an armor of UV absorbers, radical scavengers and antioxidants guarantee optimal protection of headlights and lenses from UV-induced deterioration and environmental impacts. This cutting-edge technology ensures that our coatings are quick and easy to apply, and that they are of superior quality.'),
(28, 'Si3DMatte', 'Nanolex Si3D Matte is an advanced silica-based coating formulated specifically to protect matt paint finishes and matt vinyl wraps without adding any gloss or otherwise altering their appearance. Developed in Germany, it uses the latest in low volatile content silicon (Si) technology to lay down a film of hybrid siloxane polymers and proprietary thermoplastic components that condenses rapidly to form a flexible matrix-like coating that bonds to treated surfaces at the molecular level. As a result, it provides excellent protection against bird droppings, bug splatter, brake dust, road salt and harmful UV radiation from the sun for up to two years at a time, even on daily drivers (it is impervious to cleaning chemicals and pressure washing).\n\nHowever, the benefits imparted by Nanolex Si3D Matte do not end with outstanding levels of protection and durability. Perhaps equally as importantly, treated surfaces become slicker feeling and more hydrophobic. This latter characteristic not only results in impressive beading upon contact with water, but also produces a strong self-cleaning effect (rainfall beads up and rolls off of treated surfaces, taking freshly deposited contaminants with it, akin to the Lotus Effect in nature). This results in treated bodywork staying appreciably cleaner for longer between routine washes, particularly in the winter. '),
(29, 'SiFinish', 'Nanolex SiFinish is a water-based sealant containing silica compounds that are designed to bond to painted and coated surfaces. Nanolex SiFinish offers an incredibly high-gloss shine combined with outstanding water beading performance and leaves the surface smooth to the touch. Nanolex SiFinish is designed to prevent water spotting, acting as a protective layer and lasting multiple months with just one application. Nanolex SiFinish provides excellent protection for months by itself, and when used on top of previously-applied Nanolex coatings it will prolong the durability significantly, as well as leaving the paintwork looking as if a fresh coat of sealant had just been applied. Nanolex SiFinish is designed to prevent water spotting, acting as a protective layer and lasting multiple months with just one application. Nanolex SiFinish provides excellent protection for months by itself, and when used on top of previously-applied Nanolex coatings it will prolong the durability significantly, as well as leaving the paintwork looking as if a fresh coat of sealant had just been applied.'),
(30, 'SiShield', 'Nanolex SiShield is a ceramic coating developed to provide outstanding chemical and mechanical resistancy combined with great ease of use. Nanolex SiShield provides superb corrosion protection and hardness for all painted surfaces as well as metal and hard plastics. Thanks to a very high level of hydrophobicity and density the layer formed by Nanolex SiShield will provide outstanding easy-to-clean properties. Nanolex SiShield was developed, tested and produced in Germany.'),
(31, 'Spray Sealant', 'Spray Sealant is an advanced formulation based on nanotechnology that protects and enhances all painted surfaces as well as metal and exterior plastics. Nanolex Spray Sealant is based on the chemical sol-gel process which allows the nano-scale particles of SiO2 to self-organise into an interlaced layer and form a covalent (=permanent) bond with the surface at a molecular level.\n\nSurfaces protected with a layer of Nanolex Spray Sealant are much smoother, more reflective and extremely hydrophobic. Washing is therefore much easier and less time-consuming, plus cleaning intervals are substantially increased and the overall effort to maintain a flawless finish is heavily reduced. With proper maintenance Nanolex Spray Sealant has a longevity of approximately 7,000 km on the surfaces it was applied to.\n\nAdds protection:\nEmits strong fumes\nApplication method: by Hand only\nDurability: 6 months+ (7000 km.)\nRecommended for: Cool colours & metallic/pearlescent finishes'),
(32, 'Tar Remover', 'Nanolex Tar Remover is a solvent-based specialist cleaner for the effortless removal of tar and bitumen. Free of halogenated hydrocarbons, it is suitable for all solvent-resistant surfaces and materials.\n\nApply the product undiluted to the dry surface, and allow it to react for a short time. When necessary, finish by hand and rinse off with a pressure washer appliance, or use a microfiber cloth to wipe off any residue.'),
(33, 'Textile Leather Sealant', 'Nanolex Textile and Leather Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for textile and leather while being safe for users and the environment. Surfaces sealed with this product repel oil, water and most other common kinds of liquid contaminants. Nanolex Textile & Leather Sealant can also be used on cotton, leather, polyester, or blended fabric. Nanolex Textile & Leather Sealant was developed, tested and produced in Germany.'),
(34, 'Tire & Rubber Restorer', 'Nanolex Tire & Rubber Restorer is based upon an optimized, UV resistant formulation which restores tires and rubber trim to their natural appearance. The deeply-penetrating raw materials in Nanolex Tire & Rubber Restorer provide treated surfaces with a long-lasting and original appearance.\n\nWith proper maintenance Nanolex Spray Sealant will have a durability of approximately 1000 km on the surfaces it was applied to.\n\nSpecifications:\n\nSolvent-based\nAdds protection\nUV protection\nShine level: Medium\nDurability: 3 weeks+'),
(35, 'Trim Rejuvenator', 'The exterior plastic trim parts of a car are exposed to many damaging environmental impacts. UV-radiation and heat can damage the plastic trim, turning it grey and making it brittle. Frost, salt, strong and aggressive cleaners, acid rain as well as mechanical abrasion have an extremely detrimental effect on plastic parts, and cause them deteriorate quickly. The special, deeply-penetrating ingredients of Nanolex Trim Rejuvenator ensure that the trim does not fade or become brittle. The typical effects of weathering and greying are also prevented. Nanolex Trim Rejuvantor cleanses gently and adds durability, plus it penetrates the surfaces easily and quickly without adding a greasy finish or leaving an artificial shine.'),
(36, 'Ultra Glass Sealant', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology. This coating forms a chemical bond with the glass it is applied to. Nanolex Ultra Glass sealant drastically improves visibility and safety under wet weather conditions, with superior optical clarity. Coated glass surfaces permanently repel water to an outstanding degree and require significantly less cleaning, so saving you time and money. The build up of ice on the glass surfaces is delayed, once ice has set on the surface it can be removed very easily. Raindrops are blown off by the airflow when driving speeds exceed 60 Km. The durability of Nanolex Ultra Glass Sealant is outstanding, with a longevity of at least 18 months or 30,000 km.'),
(37, 'Ultra Matte Sealant', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces. It is designed to form a long lasting chemical bond with the Matte surface, offering a molecular protection without any enhanced gloss or shine. This spray sealant is very easy to apply over all matte paints, vinyls and surfaces keeping them cleaner for longer and making washing easier. It offers immediate protection over delicate matte surfaces, leaving behind a natural flat sheen, or can be used over Nanolex Si3D Matte.'),
(38, 'Ultra Glass Sealant', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology. This coating forms a chemical bond with the glass it is applied to. Nanolex Ultra Glass sealant drastically improves visibility and safety under wet weather conditions, with superior optical clarity. Coated glass surfaces permanently repel water to an outstanding degree and require significantly less cleaning, so saving you time and money. The build up of ice on the glass surfaces is delayed, once ice has set on the surface it can be removed very easily. Raindrops are blown off by the airflow when driving speeds exceed 60 Km. The durability of Nanolex Ultra Glass Sealant is outstanding, with a longevity of at least 18 months or 30,000 km.'),
(39, 'Urban Glass Sealant', 'Nanolex Urban Glass Sealant is an advanced, solvent-based coating which forms a barrier against water, oil and grime on automotive glass surfaces. Nanolex Urban Glass Sealant combines a high-tech composite material with reactive compounds that form a fully-transparent, highly hydrophobic, non-stick coating that gives outstanding protection to glass surfaces in urban areas. Nanolex Urban Glass Sealant improves visibility and therefore driving comfort in bad weather conditions, reducing the need to use windscreen wipers and screen wash greatly. In addition grime and bug splatter can be easily washed off and de-icing requires much less effort too. Raindrops are dispersed by the airflow when driving speeds exceed 40 Km/h. The durability of Nanolex Urban Glass Sealant is excellent, with a longevity of at least 4-6 months or 6000 km. Nanolex Urban Glass Sealant was developed, tested and manufactured in Germany.'),
(40, 'WashCoat', 'Nanolex WashCoat is an incredibly quick and effective way to protect and maintain exterior automotive surfaces. WashCoat is applied to the car after washing, whilst the car is still wet. It forms a chemical bond with the paint and refreshes previously-applied protective layers. Both the gloss level of the paint and the water beading properties are highly increased after a treatment with WashCoat. Your car will also stay cleaner for longer, and will be easier to wash. WashCoat can be applied using a foam lance or a pump sprayer.'),
(41, 'Wheel Cleaner & Iron Remover', 'Nanolex Wheel Cleaner & Iron Remover is a highly effective and extremely fast-acting wheel cleaner and iron contamination remover. It is less aggressive than traditional acidic wheel cleaners, yet just as powerful.\r\n\r\nUpon contact with the surface its effective formulation dissolves all iron contamination, including harmful brake dust.\r\n\r\nAn innovative colour change mechanism - which turns the product from clear to red - indicates when the iron particles have been solved and can be safely rinsed away.\r\n\r\nNanolex Wheel Cleaner & Iron Remover also reduces the need to agitate treated surfaces, due to its unique viscous formulation and superior dwell time.'),
(42, 'Wheel Cleaner & Iron Remover', 'Nanolex Wheel Cleaner & Iron Remover is a highly effective and extremely fast-acting wheel cleaner and iron contamination remover. It is less aggressive than traditional acidic wheel cleaners, yet just as powerful.\r\n\r\nUpon contact with the surface its effective formulation dissolves all iron contamination, including harmful brake dust.\r\n\r\nAn innovative colour change mechanism - which turns the product from clear to red - indicates when the iron particles have been solved and can be safely rinsed away.\r\n\r\nNanolex Wheel Cleaner & Iron Remover also reduces the need to agitate treated surfaces, due to its unique viscous formulation and superior dwell time.'),
(57, 'WashCoat', 'Prekes aprasymas:\r\n                  '),
(74, 'valiklis', 'labai geras valiklis                  ');

-- --------------------------------------------------------

--
-- Table structure for table `aprasymaitrumpi`
--

CREATE TABLE `aprasymaitrumpi` (
  `id` int(6) NOT NULL,
  `pavadinimas` text,
  `aprasymas` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `aprasymaitrumpi`
--

INSERT INTO `aprasymaitrumpi` (`id`, `pavadinimas`, `aprasymas`) VALUES
(1, 'Convertible Top Sealant', 'Nanolex Convertible Top Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for convertible tops.'),
(2, 'EX', 'Nanolex EX guarantees that surfaces are perfectly-prepared and ready for Nanolex Sealants.'),
(3, 'Final Finish', 'The mild formulation ensures a gentle and refreshing care for all clear lacquer surfaces.'),
(4, 'Finishing-Cut', 'Nanolex Finishing Polish 2019 removes fine scratches and holograms.'),
(5, 'Glass Cleaner', 'Nanolex Glass Cleaner was developed specifically for automotive glass.'),
(6, 'Glass Polish', 'Nanolex Glass Polish is a unique mixture containing micro- abrasives which guarantee that glass surfaces are thoroughly cleansed and perfectly prepared and activated for a treatment with Nanolex Glass Sealant. Shake very well before use.'),
(7, 'Heavy-Cut Polish', 'When full correction is required, Nanolex Heavy Cut Polish reliably removes heavy defects such as random deep scratches.'),
(8, 'Insect Remover', 'Nanolex Insect Remover is a specialist alkaline cleaner for the residue-free removal of insects.'),
(9, 'Insect Remover Concentrate', 'Nanolex Insect Remover Concentrate is a specialist alkaline cleaner for the residue-free removal of insects.'),
(10, 'Interior Cleaner', 'Nanolex Interior Cleaner is designed to gently clean all interior surfaces, such as leather, vinyl and plastic.'),
(11, 'Interior Cleaner Concentrate', 'Nanolex Interior Cleaner Concentrate is designed to gently clean all interior surfaces, such as leather, vinyl and plastic.\r\n\r\n'),
(12, 'Matte Final Finish', 'Nanolex Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces.'),
(13, 'Matte Reactivating Shampoo', 'Nanolex Matte Reactivating Shampoo is a specialist car shampoo for matte paints and surfaces.'),
(14, 'Matte Spray Sealant', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces.'),
(15, 'Matte Final Finish', 'Matte Final Finish is a silicone free detailing spray which will not leave any gloss on your matte paint and surfaces.\r\n\r\n'),
(16, 'Medium-Cut 500', 'To Refine Corrected Paintwork & Remove Moderate Defects.'),
(17, 'Microfiber Wash', 'Microfiber Wash is specifically designed for microfiber towels and other accessories.'),
(18, 'Nano One', 'Nanolex Nano One is a water-based sealant that simultaneously cleanses, rejuvenates and protects automotive paint.'),
(19, 'ODEX', 'Nanolex ODEX is a scent-free, fast acting odor eliminator.'),
(20, 'Premium Paint & Alloy Sealant', 'Premium Paint & Alloy Sealant is a new-generation nanotechnology coating which protects and enhances the appearance of automotive paint in one step.'),
(21, 'Prewash Concentrate', 'Very effective, high-foaming, alkaline prewash. '),
(22, 'Pure Shampoo', 'Nanolex Pure Shampoo is a highly effective, yet extremely mild (pH-neutral), phosphate and NTA-free exterior car shampoo.'),
(23, 'Race Film Remover', 'Nanolex Race Film Remover is a highly efficient cleaner for race track related contamination.'),
(24, 'Reactivating Shampoo', 'Nanolex Reactivating Shampoo is designed to clean and protect your car in a single, easy step.'),
(25, 'Si3D', 'Based on its unique Si3D technology, Nanolex Car Care offers a range of products specifically developed and designed to fulfill the highest demands and needs of our professional customers.'),
(26, 'Si3D HD', 'Nanolex Si3D is extremely weather and chemical resistant, which in turn provides excellent corrosion protection with easy-to-clean-properties.'),
(27, 'Si3D Headlight', 'This cutting-edge technology ensures that our coatings are quick and easy to apply, and that they are of superior quality.'),
(28, 'Si3DMatte', 'Nanolex Si3D Matte is an advanced silica-based coating formulated specifically to protect matt paint finishes and matt vinyl wraps.'),
(29, 'SiFinish', 'Nanolex SiFinish is a water-based sealant containing silica compounds that are designed to bond to painted and coated surfaces.'),
(30, 'SiShield', 'Nanolex SiShield is a ceramic coating developed to provide outstanding chemical and mechanical resistancy combined with great ease of use.'),
(31, 'Spray Sealant', 'Spray Sealant is an advanced formulation based on nanotechnology that protects and enhances all painted surfaces.'),
(32, 'Tar Remover', 'Nanolex Tar Remover is a solvent-based specialist cleaner for the effortless removal of tar and bitumen.'),
(33, 'Textile Leather Sealant', 'Nanolex Textile and Leather Sealant is based on a sophisticated C6 fluorocarbon technology, guaranteeing optimal protection for textile and leather.'),
(34, 'Tire & Rubber Restorer', 'Nanolex Tire & Rubber Restorer is based upon an optimized, UV resistant formulation which restores tires and rubber trim to their natural appearance.'),
(35, 'Trim Rejuvenator', 'Nanolex Trim Rejuvantor cleanses gently and adds durability.'),
(36, 'Ultra Glass Sealant', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology.'),
(37, 'Ultra Matte Sealant', 'Matte Spray Sealant is a specialist spray sealant for matte paints and surfaces.'),
(38, 'Ultra Glass Sealant', 'Nanolex Ultra Glass Sealant is based on chemical nanotechnology.'),
(39, 'Urban Glass Sealant', 'Nanolex Urban Glass Sealant is an advanced, solvent-based coating which forms a barrier against water, oil and grime on automotive glass surfaces.'),
(40, 'WashCoat', 'Nanolex WashCoat is an incredibly quick and effective way to protect and maintain exterior automotive surfaces.'),
(41, 'Wheel Cleaner & Iron Remover', 'Nanolex Wheel Cleaner & Iron Remover is a highly effective and extremely fast-acting wheel cleaner.');

-- --------------------------------------------------------

--
-- Table structure for table `foto`
--

CREATE TABLE `foto` (
  `id_foto` int(6) NOT NULL,
  `pav` text,
  `prekes_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `foto`
--

INSERT INTO `foto` (`id_foto`, `pav`, `prekes_id`) VALUES
(1, 'Convertible_Top_200_ml_klar.jpg', 1),
(2, 'Convertible_Top_750_ml_klar.jpg', 1),
(3, 'EX_750_ml_klar.jpg', 2),
(4, 'Final_Finish_200_ml_klar.jpg', 3),
(5, 'Final_Finish_750_ml_klar.jpg', 3),
(6, 'Finishing-Cut-500_ml_black.jpg', 4),
(7, 'Glass_Cleaner_750_ml_klar.jpg', 5),
(8, 'Glass_Polish_100_ml_pe_deckel_trans.jpg', 6),
(9, 'Glass_Polish_200_ml_pe_deckel_trans.jpg', 6),
(10, 'Heavy-Cut-Polish-1000_ml_black.jpg', 7),
(11, 'Insect_Remover_750_ml.jpg', 8),
(12, 'Insect_Remover_Concentrate_1000_ml_pe_deckel_trans.jpg', 9),
(13, 'Interior_Cleaner_750_ml_klar.jpg', 10),
(14, 'Interior_Cleaner_Concentrate_750_ml_klar.jpg', 11),
(15, 'Matte_Final_Finish_750_ml_klar.jpg', 12),
(16, 'Matte_Reac_Shampoo_750_ml_klar.jpg', 13),
(17, 'Matte_Spray_Sealant_100_ml_klar.jpg', 14),
(18, 'Matte_Spray_Sealant_200_ml_klar.jpg', 14),
(19, 'Matte-Final-Finish-200ml.jpg', 15),
(20, 'Medium-Cut-500_ml_black.jpg', 16),
(21, 'Microfiber_Wash_750_ml_klar.jpg', 17),
(22, 'Nano_One_100_ml_pe_deckel_trans.jpg', 18),
(23, 'Nano_One_200_ml_pe_deckel_trans.jpg', 18),
(24, 'ODEX_200_ml_klar.jpg', 19),
(25, 'ODEX_750_ml_klar.jpg', 19),
(26, 'Premium_PA_50_ml_klar.jpg', 20),
(27, 'Premium_Paint_Alloy_100_ml_pe_deckel_trans.jpg', 20),
(28, 'Prewash_Concentrate_1000_ml_pe_deckel_trans.jpg', 21),
(29, 'Pure_Shampoo_750_ml_klar.jpg', 22),
(30, 'Race_Film_Remover_750_ml_klar.jpg', 23),
(31, 'Reac_Shampoo_750_ml_klar.jpg', 24),
(32, 'Si3D_30_ml_glas.jpg', 25),
(33, 'Si3D_50_ml_glas.jpg', 25),
(34, 'Si3D_HD_Flaschen.jpg', 26),
(35, 'Si3D_Headlight_30ml.jpg', 27),
(36, 'Si3D_Matte_30_ml_glas.jpg', 28),
(37, 'SiFinish_200_ml_pe_spruehkopf_trans.jpg', 29),
(38, 'SiShield_30ml.jpg', 30),
(39, 'Spray_Sealant_100_ml_klar.jpg', 31),
(40, 'Spray_Sealant_200_ml_klar.jpg', 31),
(41, 'Spray_Sealant_750_ml_klar.jpg', 31),
(42, 'Tar_Remover_750_ml_klar.jpg', 32),
(43, 'Textile_Leather_200_ml_klar.jpg', 33),
(44, 'Textile_Leather_750_ml_klar.jpg', 33),
(45, 'Tire_Rubber_750_ml_klar.jpg', 34),
(46, 'Trim_Rejuvenator_100_ml_klar.jpg', 35),
(47, 'Trim_Rejuvenator_200_ml_klar.jpg', 35),
(48, 'Trim_Rejuvenator_750_ml_klar.jpg', 35),
(49, 'Ultra_Glass_100_ml_pe_deckel_trans.jpg', 36),
(50, 'Ultra_Matte_50_ml_pe_deckel_trans.jpg', 37),
(51, 'Ultra_Matte_100_ml_pe_deckel_trans.jpg', 37),
(52, 'Ultra-Glass_30_ml_pe_deckel.jpg', 38),
(53, 'Urban_Glass_100_ml_pe_deckel_trans.jpg', 39),
(54, 'WashCoat_200_ml_klar.jpg', 40),
(55, 'WashCoat_750_ml_klar.jpg', 40),
(56, 'WC_IR_750_ml_klar.jpg', 41),
(57, 'preke', 49),
(58, 'preke', 49);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(12) NOT NULL,
  `user` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `user`, `password`) VALUES
(1, 'admin', 'admin'),
(2, 'admin', 'admin');

-- --------------------------------------------------------

--
-- Table structure for table `uzklausos`
--

CREATE TABLE `uzklausos` (
  `id` int(11) NOT NULL,
  `vardas` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `elPastas` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `tema` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `klausimas` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `uzklausos`
--

INSERT INTO `uzklausos` (`id`, `vardas`, `elPastas`, `tema`, `klausimas`) VALUES
(1, 'Valdemaras Litvaitis', 'valdemaras@litvaitis.com', 'apie', 'klausimai'),
(2, 'Valdemaras Litvaitis', 'valdemaras@litvaitis.com', 'prekes', 'klausimai apie prekes');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `aprasymai`
--
ALTER TABLE `aprasymai`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `aprasymaiGeri`
--
ALTER TABLE `aprasymaiGeri`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `aprasymaitrumpi`
--
ALTER TABLE `aprasymaitrumpi`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `foto`
--
ALTER TABLE `foto`
  ADD PRIMARY KEY (`id_foto`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `uzklausos`
--
ALTER TABLE `uzklausos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `aprasymai`
--
ALTER TABLE `aprasymai`
  MODIFY `id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;

--
-- AUTO_INCREMENT for table `aprasymaiGeri`
--
ALTER TABLE `aprasymaiGeri`
  MODIFY `id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;

--
-- AUTO_INCREMENT for table `aprasymaitrumpi`
--
ALTER TABLE `aprasymaitrumpi`
  MODIFY `id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `foto`
--
ALTER TABLE `foto`
  MODIFY `id_foto` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=59;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(12) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `uzklausos`
--
ALTER TABLE `uzklausos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
